#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb 15 10:50:42 2024

@author:  btsund
"""
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from joblib import Parallel, delayed

def minimum_image_distance(r_i, r_j, box):
    # Compute the distance vector between two particles, applying PBC
    distance_vector = r_j - r_i
    distance_vector -= box * np.round(distance_vector / box)  # Apply minimum image convention
    distance = np.linalg.norm(distance_vector)
    return distance


def compute_distance_matrix(pos, box):
    natoms = len(pos)
    distance_matrix = np.zeros((natoms, natoms))

    for i in range(natoms):
        for j in range(i + 1, natoms):
            dist = minimum_image_distance(pos[i], pos[j], box)
            distance_matrix[i, j] = dist
            distance_matrix[j, i] = dist  # Symmetric matrix

    return distance_matrix


def compute_rdf_for_configuration(pos, box, rcut, dr, res_i):
    natoms = len(pos)
    distance_matrix = compute_distance_matrix(pos, box)

    rdf_local = np.zeros([int(rcut / dr)]*3)
    count_local = np.zeros([int(rcut / dr)]*3)

    for j in range(natoms):
        for k in range(j + 1, natoms):
            r_jk = distance_matrix[j, k]
            if r_jk > rcut:
                continue

            for h in range(k + 1, natoms):
                r_jh = distance_matrix[j, h]
                r_kh = distance_matrix[k, h]

                if r_jh > rcut or r_kh > rcut:
                    continue

                # Triangle inequalities - speeds up calculation if one side is longer than the sum of the other two
                if r_jk > (r_jh + r_kh) or r_jh > (r_jk + r_kh) or r_kh > (r_jk + r_jh):
                    continue

                b, c, a = sorted([r_jk, r_jh, r_kh])
                res = (res_i[j] + res_i[k] + res_i[h])
                rdf_local[int(a / dr), int(b / dr), int(c / dr)] += res
                count_local[int(a / dr), int(b / dr), int(c / dr)] += 1
                rdf_local[int(a / dr), int(c / dr), int(b / dr)] += res
                count_local[int(a / dr), int(c / dr), int(b / dr)] += 1
                rdf_local[int(b / dr), int(a / dr), int(c / dr)] += res
                count_local[int(b / dr), int(a / dr), int(c / dr)] += 1
                rdf_local[int(b / dr), int(c / dr), int(a / dr)] += res
                count_local[int(b / dr), int(c / dr), int(a / dr)] += 1
                rdf_local[int(c / dr), int(b / dr), int(a / dr)] += res
                count_local[int(c / dr), int(b / dr), int(a / dr)] += 1
                rdf_local[int(c / dr), int(a / dr), int(b / dr)] += res
                count_local[int(c / dr), int(a / dr), int(b / dr)] += 1

    return rdf_local, count_local


def main(pos, box, rcut, dr, res):
    results = Parallel(n_jobs=-1)(delayed(compute_rdf_for_configuration)(pos[i], box, rcut, dr, res[i])
                                   for i in range(len(pos)))

    rdf = np.sum([result[0] for result in results], axis=0)
    count = np.sum([result[1] for result in results], axis=0)

    return rdf, count


def load_trajectory(filepath, num_timesteps, dump_freq, num_atoms, filepath2):
    num_frames = num_timesteps // dump_freq + 1 \
        if num_timesteps % dump_freq == 0 else num_timesteps // dump_freq
    with open(filepath, 'r') as file:
        with open(filepath2, 'r') as resfile:
            for t in range(num_frames):
                try:
                   if int(t) ==0: # fix the ranges to fit your file format
                       for _ in range(1):  # Skipping metadata lines
                           num_atoms = int(next(file).split()[0])
                           positions = np.zeros((num_frames, num_atoms, 3))
                           res = np.zeros((num_frames, num_atoms))
                           cell = next(file).split()[1:11]
                   if int(t) !=0:
                       for _ in range(1):  # Skipping metadata lines
                           next(file)
                       for _ in range(1):  # Skipping metadata lines
                           cell = next(file).split()[1:11]
                   residual = 0
                   for i in range(num_atoms):
                       atom_data = next(file).split()
                       for j in range(3):
                           LINE = next(resfile).split()
                           residual += (float(LINE[1])-float(LINE[2]))**2
                       res[t,int(i)] = np.sqrt(residual)
                       residual=0
                       x, y, z = float(atom_data[1]), float(atom_data[2]), float(atom_data[3])
                       positions[t, int(i)] = [x, y, z]
                except StopIteration:
                    num_frames = t * dump_freq
                    break
    return positions, num_frames, num_atoms, cell, res

# Directory containing the files
filename = "/Users/btsund/Downloads/1500K.OUTCAR.xyzf"
filename = "/Users/btsund/Downloads/750K.OUTCAR.xyzf"
filename2 = "/Users/btsund/Downloads/compare_bF_1500K.txt"
filename2 = "/Users/btsund/Downloads/compare_bF_SPC_cutoff_4608.txt"
filename = "/Users/btsund/Downloads/all.OUTCAR.100.xyzf"
filename2 = "/Users/btsund/Downloads/compare_bF_SPC_cutoff_69408.txt"


inner_cutoff = 0
outer_cutoff = 6
dr = .1
iofreq = 1
timesteps = 23 # total timesteps
pos, timesteps, atoms, cellv, res = load_trajectory(filename, timesteps, iofreq,1, filename2)
cell = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0.0]])
for i in range(3):
    for j in range(3):
        cell[i,j] = float(cellv[i*3+j])
ortholat = np.array([cell[0,0],cell[1,1],cell[2,2]])
for i in range(len(pos)):
    pos[i] = pos[i] % ortholat
    pos[i] -= np.floor(pos[i] / ortholat) * ortholat
rdf, count = main(pos, ortholat, outer_cutoff, dr, res)
volume = rdf
for j in range(int(outer_cutoff / dr)):
        for k in range(int(outer_cutoff / dr)):
            for h in range(int(outer_cutoff / dr)):
                volume[j,k,h] = rdf[j,k,h] / (count[j,k,h]+1)
minval = np.min(count[count!=0])
maxval = np.amax(count, axis=None)
res = len(volume[0])
mincol = np.log(np.min(volume[volume!=0])*2)
maxcol = np.log(np.amax(volume, axis=None)*.8)
# Define frames

fig = go.Figure(frames=[go.Frame(data=go.Surface(
    z=count[k,:,:],
    surfacecolor=(np.log(volume[k])),
    y=np.linspace(inner_cutoff, outer_cutoff, num=len(volume[0]) + 1),
    x=np.linspace(inner_cutoff, outer_cutoff, num=len(volume[0]) + 1),
    cmin=mincol, cmax=maxcol),
    name=str(k))
    for k in range(int(res))])

# Add data to be displayed before animation starts
fig.add_trace(go.Surface(
    z=count[:,:,0],
    y=np.linspace(inner_cutoff, outer_cutoff, num=len(volume[0]) + 1),
    x=np.linspace(inner_cutoff, outer_cutoff, num=len(volume[0]) + 1),
    surfacecolor=(volume[0]),
    cmin=mincol, cmax=maxcol, colorscale='RdBu_r',
    colorbar=dict(thickness=20, ticklen=4)))


def frame_args(duration):
    return {"frame": {"duration": duration},
            "mode": "immediate",
            "fromcurrent": True,
            "transition": {"duration": duration, "easing": "linear"}, }


sliders = [
    {
        "pad": {"b": 10, "t": 60},
        "len": 0.9,
        "x": 0.1,
        "y": 0,
        "steps": [
            {
                "args": [[f.name], frame_args(0)],
                "label": str(k),
                "method": "animate",
            }
            for k, f in enumerate(fig.frames)
        ],
    }
]

# Layout
fig.update_layout(
    title='3 Body Energy visualization (kcal/mol/atom)',
    width=900,
    height=900,
    scene=dict(
        zaxis=dict(range=[minval, maxval+1], autorange=False),
        yaxis=dict(nticks=4, range=[inner_cutoff, outer_cutoff], ),
        xaxis=dict(nticks=4, range=[inner_cutoff, outer_cutoff], ),
        aspectmode='cube',
        aspectratio=dict(x=1, y=1, z=100)),
    updatemenus=[
        {
            "buttons": [
                {
                    "args": [None, frame_args(50)],
                    "label": "&#9654;",  # play symbol
                    "method": "animate",
                },
                {
                    "args": [[None], frame_args(0)],
                    "label": "&#9724;",  # pause symbol
                    "method": "animate",
                },
            ],
            "direction": "left",
            "pad": {"r": 10, "t": 70},
            "type": "buttons",
            "x": 0.1,
            "y": 0,
        }
    ],
    sliders=sliders
)

fig.update_layout(scene=dict(
    xaxis_title='1, 2 Distance (pm)',
    yaxis_title='1, 3 Distance (pm)',
    zaxis_title='2, 3 Distance (pm)'),
    yaxis=dict(nticks=4, range=[inner_cutoff, outer_cutoff], ),
    xaxis=dict(nticks=4, range=[inner_cutoff, outer_cutoff], ),
)
fig.show()
